import random

# tense description: 1 = simple preesent (presente); 2 = simple past (pretérito perfecto simple);
# 3 = imperfect (pretérito imperfecto); 4 = simple future (futuro); 5 = conditional (condicional);
# 6 = gerund (gerundio); 7 = participle (participio); 8 = translation (traducción) 

verbDict = {1: {1: {1: 'caigo', 2: 'caes', 3: 'cae', 4: 'caemos', 5: 'caéis', 6: 'caen'},
                  2: {1: 'caí', 2: 'caíste', 3: 'cayó', 4: 'caímos', 5: 'caísteis', 6: 'cayeron'},
                  3: {1: 'caía', 2: 'caías', 3: 'caía', 4: 'caíamos', 5: 'caíaís', 6: 'caían'},
                  4: {1: 'caeré', 2: 'caerás', 3: 'caerá', 4: 'caeremos', 5: 'caeréis', 6: 'caerán'},
                  5: {1: 'caería', 2: 'caerías', 3: 'caería', 4: 'caeríamos', 5: 'caeríais', 6: 'caerían'},
                  6: {1: 'cayendo', 2: 'cayendo', 3: 'cayendo', 4: 'cayendo', 5: 'cayendo', 6: 'cayendo'},
                  7: {1: 'caído', 2: 'caído', 3: 'caído', 4: 'caído', 5: 'caído', 6: 'caído'}},
              2: {1: {1: 'consigo', 2: 'consigues', 3: 'consigue', 4: 'conseguimos', 5: 'conseguís', 6: 'consiguen'},
                  2: {1: 'conseguí', 2: 'conseguiste', 3: 'consiguió', 4: 'conseguimos', 5: 'conseguisteis', 6: 'consiguieron'},
                  3: {1: 'conseguía', 2: 'conseguías', 3: 'conseguía', 4: 'conseguíamos', 5: 'conseguíais', 6: 'conseguían'},
                  4: {1: 'conseguiré', 2: 'conseguirás', 3: 'conseguirá', 4: 'conseguiremos', 5: 'conseguiréis', 6: 'conseguirán'},
                  5: {1: 'conseguiría', 2: 'conseguirías', 3: 'conseguiría', 4: 'conseguiríamos', 5: 'conseguiríais', 6: 'conseguirían'},
                  6: {1: 'consiguiendo', 2: 'consiguiendo', 3: 'consiguiendo', 4: 'consiguiendo', 5: 'consiguiendo', 6: 'consiguiendo'},
                  7: {1: 'conseguido', 2: 'conseguido', 3: 'conseguido', 4: 'conseguido', 5: 'conseguido', 6: 'conseguido'}},
              3: {1: {1: 'almuerzo', 2: 'almuerzas', 3: 'almuerza', 4: 'almorzamos', 5: 'almorzáis', 6: 'almuerzan'},
                  2: {1: 'almorcé', 2: 'almorzaste', 3: 'almorzó', 4: 'almorzamos', 5: 'almorzasteis', 6: 'almorzaron'},
                  3: {1: 'almorzaba', 2: 'almorzabas', 3: 'almorzaba', 4: 'almorzábamos', 5: 'almorzabais', 6: 'almorzaban'},
                  4: {1: 'almorzaré', 2: 'almorzarás', 3: 'almorzará', 4: 'almorzaremos', 5: 'almorzaréis', 6: 'almorzarán'},
                  5: {1: 'almorzaría', 2: 'almorzarías', 3: 'almorzaría', 4: 'almorzaríamos', 5: 'almorzaríais', 6: 'almorzarían'},
                  6: {1: 'almorzando', 2: 'almorzando', 3: 'almorzando', 4: 'almorzando', 5: 'almorzando', 6: 'almorzando'},
                  7: {1: 'almorzado', 2: 'almorzado', 3: 'almorzado', 4: 'almorzado', 5: 'almorzado', 6: 'almorzado'}},
              4: {1: {1: 'comienzo', 2: 'comienzas', 3: 'comienza', 4: 'comenzamos', 5: 'comenzáis', 6: 'comienzan'},
                  2: {1: 'comencé', 2: 'comenzaste', 3: 'comenzó', 4: 'comenzamos', 5: 'comenzasteis', 6: 'comenzaron'},
                  3: {1: 'comenzaba', 2: 'comenzabas', 3: 'comenzaba', 4: 'comenzábamos', 5: 'comenzabais', 6: 'comenzaban'},
                  4: {1: 'comenzaré', 2: 'comenzarás', 3: 'comenzará', 4: 'comenzaremos', 5: 'comenzaréis', 6: 'comenzarán'},
                  5: {1: 'comenzaría', 2: 'comenzarías', 3: 'comenzaría', 4: 'comenzaríamos', 5: 'comenzaríais', 6: 'comenzarían'},
                  6: {1: 'comenzando', 2: 'comenzando', 3: 'comenzando', 4: 'comenzando', 5: 'comenzando', 6: 'comenzando'},
                  7: {1: 'comenzado', 2: 'comenzado', 3: 'comenzado', 4: 'comenzado', 5: 'comenzado', 6: 'comenzado'}},
              5: {1: {1: 'conduzco', 2: 'conduces', 3: 'conduce', 4: 'conducimos', 5: 'conducís', 6: 'conducen'},
                  2: {1: 'conduje', 2: 'condujiste', 3: 'condujo', 4: 'condujimos', 5: 'condujisteis', 6: 'condujeron'},
                  3: {1: 'conducía', 2: 'conducías', 3: 'conducía', 4: 'conducíamos', 5: 'conducíais', 6: 'conducían'},
                  4: {1: 'conduciré', 2: 'conducirás', 3: 'conducirá', 4: 'conduciremos', 5: 'conduciréis', 6: 'conducirán'},
                  5: {1: 'conduciría', 2: 'conducirías', 3: 'conduciría', 4: 'conduciríamos', 5: 'conduciríais', 6: 'conducirían'},
                  6: {1: 'conduciendo', 2: 'conduciendo', 3: 'conduciendo', 4: 'conduciendo', 5: 'conduciendo', 6: 'conduciendo'},
                  7: {1: 'conducido', 2: 'conducido', 3: 'conducido', 4: 'conducido', 5: 'conducido', 6: 'conducido'}},
              6: {1: {1: 'pruebo', 2: 'pruebas', 3: 'prueba', 4: 'probamos', 5: 'probáis', 6: 'prueban'},
                  2: {1: 'probé', 2: 'probaste', 3: 'probó', 4: 'probamos', 5: 'probasteis', 6: 'probaron'},
                  3: {1: 'probaba', 2: 'probabas', 3: 'probaba', 4: 'probábamos', 5: 'probabais', 6: 'probaban'},
                  4: {1: 'probaré', 2: 'probarás', 3: 'probará', 4: 'probaremos', 5: 'probaréis', 6: 'probarán'},
                  5: {1: 'probaría', 2: 'probarías', 3: 'probaría', 4: 'probaríamos', 5: 'probaríais', 6: 'probarían'},
                  6: {1: 'probando', 2: 'probando', 3: 'probando', 4: 'probando', 5: 'probando', 6: 'probando'},
                  7: {1: 'probado', 2: 'probado', 3: 'probado', 4: 'probado', 5: 'probado', 6: 'probado'}},
              7: {1: {1: 'juego', 2: 'juegas', 3: 'juega', 4: 'jugamos', 5: 'jugáis', 6: 'juegan'},
                  2: {1: 'jugué', 2: 'jugaste', 3: 'jugó', 4: 'jugamos', 5: 'jugasteis', 6: 'jugaron'},
                  3: {1: 'jugaba', 2: 'jugabas', 3: 'jugaba', 4: 'jugábamos', 5: 'jugabais', 6: 'jugaban'},
                  4: {1: 'jugaré', 2: 'jugarás', 3: 'jugará', 4: 'jugaremos', 5: 'jugaréis', 6: 'jugarán'},
                  5: {1: 'jugaría', 2: 'jugarías', 3: 'jugaría', 4: 'jugaríamos', 5: 'jugaríais', 6: 'jugarían'},
                  6: {1: 'jugando', 2: 'jugando', 3: 'jugando', 4: 'jugando', 5: 'jugando', 6: 'jugando'},
                  7: {1: 'jugado', 2: 'jugado', 3: 'jugado', 4: 'jugado', 5: 'jugado', 6: 'jugado'}},
              8: {1: {1: 'creo', 2: 'crees', 3: 'cree', 4: 'creemos', 5: 'creéis', 6: 'creen'},
                  2: {1: 'creí', 2: 'creíste', 3: 'creyó', 4: 'creímos', 5: 'creísteis', 6: 'creyeron'},
                  3: {1: 'creía', 2: 'creías', 3: 'creía', 4: 'creíamos', 5: 'creíais', 6: 'creían'},
                  4: {1: 'creeré', 2: 'creerás', 3: 'creerá', 4: 'creeremos', 5: 'creeréis', 6: 'creerán'},
                  5: {1: 'creería', 2: 'creerías', 3: 'creería', 4: 'creeríamos', 5: 'creeríais', 6: 'creerían'},
                  6: {1: 'creyendo', 2: 'creyendo', 3: 'creyendo', 4: 'creyendo', 5: 'creyendo', 6: 'creyendo'},
                  7: {1: 'creído', 2: 'creído', 3: 'creído', 4: 'creído', 5: 'creído', 6: 'creído'}},
              9: {1: {1: 'vuelvo', 2: 'vuelves', 3: 'vuelve', 4: 'volvemos', 5: 'volvéis', 6: 'vuelven'},
                  2: {1: 'volví', 2: 'volviste', 3: 'volvió', 4: 'volvimos', 5: 'volvisteis', 6: 'volvieron'},
                  3: {1: 'volvía', 2: 'volvías', 3: 'volvía', 4: 'volvíamos', 5: 'volvíais', 6: 'volvían'},
                  4: {1: 'volveré', 2: 'volverás', 3: 'volverá', 4: 'volveremos', 5: 'volveréis', 6: 'volverán'},
                  5: {1: 'volvería', 2: 'volverías', 3: 'volvería', 4: 'volveríamos', 5: 'volveríais', 6: 'volverían'},
                  6: {1: 'volviendo', 2: 'volviendo', 3: 'volviendo', 4: 'volviendo', 5: 'volviendo', 6: 'volviendo'},
                  7: {1: 'vuelto', 2: 'vuelto', 3: 'vuelto', 4: 'vuelto', 5: 'vuelto', 6: 'vuelto'}},
              10: {1: {1: 'sirvo', 2: 'sirves', 3: 'sirve', 4: 'servimos', 5: 'servís', 6: 'sirven'},
                  2: {1: 'serví', 2: 'serviste', 3: 'sirvió', 4: 'servimos', 5: 'servisteis', 6: 'sirvieron'},
                  3: {1: 'servía', 2: 'servías', 3: 'servía', 4: 'servíamos', 5: 'servíais', 6: 'servían'},
                  4: {1: 'serviré', 2: 'servirás', 3: 'servirá', 4: 'serviremos', 5: 'serviréis', 6: 'servirán'},
                  5: {1: 'serviría', 2: 'servirías', 3: 'serviría', 4: 'serviríamos', 5: 'serviríais', 6: 'servirían'},
                  6: {1: 'sirviendo', 2: 'sirviendo', 3: 'sirviendo', 4: 'sirviendo', 5: 'sirviendo', 6: 'sirviendo'},
                  7: {1: 'servido', 2: 'servido', 3: 'servido', 4: 'servido', 5: 'servido', 6: 'servido'}},
              11: {1: {1: 'leo', 2: 'lees', 3: 'lee', 4: 'leemos', 5: 'leéis', 6: 'leen'},
                  2: {1: 'leí', 2: 'leíste', 3: 'leyó', 4: 'leímos', 5: 'leísteis', 6: 'leyeron'},
                  3: {1: 'leía', 2: 'leías', 3: 'leía', 4: 'leíamos', 5: 'leíais', 6: 'leían'},
                  4: {1: 'leeré', 2: 'leerás', 3: 'leerá', 4: 'leeremos', 5: 'leeréis', 6: 'leerán'},
                  5: {1: 'leería', 2: 'leerías', 3: 'leería', 4: 'leeríamos', 5: 'leeríais', 6: 'leerían'},
                  6: {1: 'leyendo', 2: 'leyendo', 3: 'leyendo', 4: 'leyendo', 5: 'leyendo', 6: 'leyendo'},
                  7: {1: 'leído', 2: 'leído', 3: 'leído', 4: 'leído', 5: 'leído', 6: 'leído'}},
              12: {1: {1: 'busco', 2: 'buscas', 3: 'busca', 4: 'buscamos', 5: 'buscáis', 6: 'buscan'},
                  2: {1: 'busqué', 2: 'buscaste', 3: 'buscó', 4: 'buscamos', 5: 'buscasteis', 6: 'buscaron'},
                  3: {1: 'buscaba', 2: 'buscabas', 3: 'buscaba', 4: 'buscabamos', 5: 'buscabais', 6: 'buscaban'},
                  4: {1: 'buscaré', 2: 'buscarás', 3: 'buscará', 4: 'buscaremos', 5: 'buscaréis', 6: 'buscarán'},
                  5: {1: 'buscaría', 2: 'buscarías', 3: 'buscaría', 4: 'buscaríamos', 5: 'buscaríais', 6: 'buscarían'},
                  6: {1: 'buscando', 2: 'buscando', 3: 'buscando', 4: 'buscando', 5: 'buscando', 6: 'buscando'},
                  7: {1: 'buscado', 2: 'buscado', 3: 'buscado', 4: 'buscado', 5: 'buscado', 6: 'buscado'}},
              13: {1: {1: 'apago', 2: 'apagas', 3: 'apaga', 4: 'apagamos', 5: 'apagáis', 6: 'apagan'},
                  2: {1: 'apagué', 2: 'apagaste', 3: 'apagó', 4: 'apagamos', 5: 'apagasteis', 6: 'apagaron'},
                  3: {1: 'apagaba', 2: 'apagabas', 3: 'apagaba', 4: 'apagábamos', 5: 'apagabais', 6: 'apagaban'},
                  4: {1: 'apagaré', 2: 'apagarás', 3: 'apagará', 4: 'apagaremos', 5: 'apagréis', 6: 'apagarán'},
                  5: {1: 'apagaría', 2: 'apagarías', 3: 'apagaría', 4: 'apagaríamos', 5: 'apagaríais', 6: 'apagarían'},
                  6: {1: 'apagando', 2: 'apagando', 3: 'apagando', 4: 'apagando', 5: 'apagando', 6: 'apagando'},
                  7: {1: 'apagado', 2: 'apagado', 3: 'apagado', 4: 'apagado', 5: 'apagado', 6: 'apagado'}},
              14: {1: {1: 'he', 2: 'has', 3: 'ha', 4: 'hemos', 5: 'habéis', 6: 'han'},
                  2: {1: 'hube', 2: 'hubiste', 3: 'hubo', 4: 'hubimos', 5: 'hubisteis', 6: 'hubieron'},
                  3: {1: 'había', 2: 'habías', 3: 'había', 4: 'habíamos', 5: 'habíais', 6: 'habían'},
                  4: {1: 'habré', 2: 'habrás', 3: 'habrá', 4: 'habremos', 5: 'habréis', 6: 'habrán'},
                  5: {1: 'habría', 2: 'habrías', 3: 'habría', 4: 'habríamos', 5: 'habríais', 6: 'habrían'},
                  6: {1: 'habiendo', 2: 'habiendo', 3: 'habiendo', 4: 'habiendo', 5: 'habiendo', 6: 'habiendo'},
                  7: {1: 'habido', 2: 'habido', 3: 'habido', 4: 'habido', 5: 'habido', 6: 'habido'}},
              15: {1: {1: 'oigo', 2: 'oyes', 3: 'oye', 4: 'oímos', 5: 'oís', 6: 'oyen'},
                  2: {1: 'oí', 2: 'oíste', 3: 'oyó', 4: 'oímos', 5: 'oísteis', 6: 'oyeron'},
                  3: {1: 'oía', 2: 'oías', 3: 'oía', 4: 'oíamos', 5: 'oíais', 6: 'oían'},
                  4: {1: 'oiré', 2: 'oirás', 3: 'oirá', 4: 'oiremos', 5: 'oiréis', 6: 'oirán'},
                  5: {1: 'oiría', 2: 'oirías', 3: 'oiría', 4: 'oiríamos', 5: 'oiríais', 6: 'oirían'},
                  6: {1: 'oyendo', 2: 'oyendo', 3: 'oyendo', 4: 'oyendo', 5: 'oyendo', 6: 'oyendo'},
                  7: {1: 'oído', 2: 'oído', 3: 'oído', 4: 'oído', 5: 'oído', 6: 'oído'}},
              16: {1: {1: 'recojo', 2: 'recoges', 3: 'recoge', 4: 'recogemos', 5: 'recogéis', 6: 'recogen'},
                  2: {1: 'recogí', 2: 'recogiste', 3: 'recogió', 4: 'recogimos', 5: 'recogisteis', 6: 'recogieron'},
                  3: {1: 'recogía', 2: 'recogías', 3: 'recogía', 4: 'recogíamos', 5: 'recogíais', 6: 'recogían'},
                  4: {1: 'recogeré', 2: 'recogerás', 3: 'recogerá', 4: 'recogeremos', 5: 'recogeréis', 6: 'recogerán'},
                  5: {1: 'recogería', 2: 'recogerías', 3: 'recogería', 4: 'recogeríamos', 5: 'recogeríais', 6: 'recogerían'},
                  6: {1: 'recogiendo', 2: 'recogiendo', 3: 'recogiendo', 4: 'recogiendo', 5: 'recogiendo', 6: 'recogiendo'},
                  7: {1: 'recogido', 2: 'recogido', 3: 'recogido', 4: 'recogido', 5: 'recogido', 6: 'recogido'}},
              17: {1: {1: 'toco', 2: 'tocas', 3: 'toca', 4: 'tocamos', 5: 'tocáis', 6: 'tocan'},
                  2: {1: 'toqué', 2: 'tocaste', 3: 'tocó', 4: 'tocamos', 5: 'tocasteis', 6: 'tocaron'},
                  3: {1: 'tocaba', 2: 'tocabas', 3: 'tocaba', 4: 'tocábamos', 5: 'tocabais', 6: 'tocaban'},
                  4: {1: 'tocaré', 2: 'tocarás', 3: 'tocará', 4: 'tocaremos', 5: 'tocaréis', 6: 'tocarán'},
                  5: {1: 'tocaría', 2: 'tocarías', 3: 'tocaría', 4: 'tocaríamos', 5: 'tocaríais', 6: 'tocarían'},
                  6: {1: 'tocando', 2: 'tocando', 3: 'tocando', 4: 'tocando', 5: 'tocando', 6: 'tocando'},
                  7: {1: 'tocado', 2: 'tocado', 3: 'tocado', 4: 'tocado', 5: 'tocado', 6: 'tocado'}},
              18: {1: {1: 'empiezo', 2: 'empiezas', 3: 'empieza', 4: 'empezamos', 5: 'empezáis', 6: 'empiezan'},
                  2: {1: 'empecé', 2: 'empezaste', 3: 'empezó', 4: 'empezamos', 5: 'empezasteis', 6: 'empezaron'},
                  3: {1: 'empezaba', 2: 'empezabas', 3: 'empezaba', 4: 'empezábamos', 5: 'empezabais', 6: 'empezaban'},
                  4: {1: 'empezaré', 2: 'empezarás', 3: 'empezará', 4: 'empezaremos', 5: 'empezaréis', 6: 'empezarán'},
                  5: {1: 'empezaría', 2: 'empezarías', 3: 'empezaría', 4: 'empezaríamos', 5: 'empezaríais', 6: 'empezarían'},
                  6: {1: 'empezando', 2: 'empezando', 3: 'empezando', 4: 'empezando', 5: 'empezando', 6: 'empezando'},
                  7: {1: 'empezado', 2: 'empezado', 3: 'empezado', 4: 'empezado', 5: 'empezado', 6: 'empezado'}},
              19: {1: {1: 'quepo', 2: 'cabes', 3: 'cabe', 4: 'cabemos', 5: 'cabéis', 6: 'caben'},
                  2: {1: 'cupe', 2: 'cupiste', 3: 'cupo', 4: 'cupimos', 5: 'cupisteis', 6: 'cupieron'},
                  3: {1: 'cabía', 2: 'cabías', 3: 'cabía', 4: 'cabíabamos', 5: 'cabíais', 6: 'cabían'},
                  4: {1: 'cabré', 2: 'cabrás', 3: 'cabrá', 4: 'cabremos', 5: 'empezaréis', 6: 'empezarán'},
                  5: {1: 'cabría', 2: 'cabrías', 3: 'cabría', 4: 'cabríamos', 5: 'cabréis', 6: 'cabrán'},
                  6: {1: 'cabiendo', 2: 'cabiendo', 3: 'cabiendo', 4: 'cabiendo', 5: 'cabiendo', 6: 'cabiendo'},
                  7: {1: 'cabido', 2: 'cabido', 3: 'cabido', 4: 'cabido', 5: 'cabido', 6: 'cabido'}},
              20: {1: {1: 'llego', 2: 'llegas', 3: 'llega', 4: 'llegamos', 5: 'llegáis', 6: 'llegan'},
                  2: {1: 'llegué', 2: 'llegaste', 3: 'llegó', 4: 'llegamos', 5: 'llegasteis', 6: 'llegaron'},
                  3: {1: 'llegaba', 2: 'llegabas', 3: 'llegaba', 4: 'llegábamos', 5: 'llegabais', 6: 'llegaban'},
                  4: {1: 'llegaré', 2: 'llegarás', 3: 'llegará', 4: 'llegaremos', 5: 'llegaréis', 6: 'llegarán'},
                  5: {1: 'llegaría', 2: 'llegarías', 3: 'llegaría', 4: 'llegaríamos', 5: 'llegaríais', 6: 'llegarían'},
                  6: {1: 'llegando', 2: 'llegando', 3: 'llegando', 4: 'llegando', 5: 'llegando', 6: 'llegando'},
                  7: {1: 'llegado', 2: 'llegado', 3: 'llegado', 4: 'llegado', 5: 'llegado', 6: 'llegado'}},
              21: {1: {1: 'explico', 2: 'explicas', 3: 'explica', 4: 'explicamos', 5: 'explicáis', 6: 'explican'},
                  2: {1: 'expliqué', 2: 'explicaste', 3: 'explicó', 4: 'explicamos', 5: 'explicasteis', 6: 'explicaron'},
                  3: {1: 'explicaba', 2: 'explicabas', 3: 'explicaba', 4: 'explicábamos', 5: 'explicabais', 6: 'explicaban'},
                  4: {1: 'explicaré', 2: 'explicarás', 3: 'explicará', 4: 'explicaremos', 5: 'explicaréis', 6: 'explicarán'},
                  5: {1: 'explicaría', 2: 'explicarías', 3: 'explicaría', 4: 'explicaríamos', 5: 'explicaríais', 6: 'explicarían'},
                  6: {1: 'explicando', 2: 'explicando', 3: 'explicando', 4: 'explicando', 5: 'explicando', 6: 'explicando'},
                  7: {1: 'explicado', 2: 'explicado', 3: 'explicado', 4: 'explicado', 5: 'explicado', 6: 'explicado'}},
              22: {1: {1: 'saco', 2: 'sacas', 3: 'saca', 4: 'sacamos', 5: 'sacáis', 6: 'sacan'},
                  2: {1: 'saqué', 2: 'sacaste', 3: 'sacó', 4: 'sacamos', 5: 'sacasteis', 6: 'sacaron'},
                  3: {1: 'sacaba', 2: 'sacabas', 3: 'sacaba', 4: 'sacábamos', 5: 'sacabais', 6: 'sacaban'},
                  4: {1: 'sacaré', 2: 'sacarás', 3: 'sacará', 4: 'sacaremos', 5: 'sacaréis', 6: 'sacarán'},
                  5: {1: 'sacaría', 2: 'sacarías', 3: 'sacaría', 4: 'sacaríamos', 5: 'sacaríais', 6: 'sacarían'},
                  6: {1: 'sacando', 2: 'sacando', 3: 'sacando', 4: 'sacando', 5: 'sacando', 6: 'sacando'},
                  7: {1: 'sacado', 2: 'sacado', 3: 'sacado', 4: 'sacado', 5: 'sacado', 6: 'sacado'}},
              23: {1: {1: 'recuerdo', 2: 'recuerdas', 3: 'recuerda', 4: 'recordamos', 5: 'recordáis', 6: 'recuerdan'},
                  2: {1: 'recordé', 2: 'recordaste', 3: 'recordó', 4: 'recordamos', 5: 'recordasteis', 6: 'recordaron'},
                  3: {1: 'recordaba', 2: 'recordabas', 3: 'recordaba', 4: 'recordábamos', 5: 'recordabais', 6: 'recordaban'},
                  4: {1: 'recordaré', 2: 'recordarás', 3: 'recordará', 4: 'recordaremos', 5: 'recordaréis', 6: 'recordarán'},
                  5: {1: 'recordaría', 2: 'recordarías', 3: 'recordaría', 4: 'recordaríamos', 5: 'recordaríais', 6: 'recordarían'},
                  6: {1: 'recordando', 2: 'recordando', 3: 'recordando', 4: 'recordando', 5: 'recordando', 6: 'recordando'},
                  7: {1: 'recordado', 2: 'recordado', 3: 'recordado', 4: 'recordado', 5: 'recordado', 6: 'recordado'}},
              24: {1: {1: 'muestro', 2: 'muestras', 3: 'muestra', 4: 'mostramos', 5: 'mostráis', 6: 'muestran'},
                  2: {1: 'mostré', 2: 'mostraste', 3: 'mostró', 4: 'mostramos', 5: 'mostrasteis', 6: 'mostraron'},
                  3: {1: 'mostraba', 2: 'mostrabas', 3: 'mostraba', 4: 'mostrábamos', 5: 'mostrabais', 6: 'mostraban'},
                  4: {1: 'mostraré', 2: 'mostrarás', 3: 'mostrará', 4: 'mostraremos', 5: 'mostraréis', 6: 'mostrarán'},
                  5: {1: 'mostraría', 2: 'mostrarías', 3: 'mostraría', 4: 'mostraríamos', 5: 'mostraríais', 6: 'mostrarían'},
                  6: {1: 'mostrando', 2: 'mostrando', 3: 'mostrando', 4: 'mostrando', 5: 'mostrando', 6: 'mostrando'},
                  7: {1: 'mostrado', 2: 'mostrado', 3: 'mostrado', 4: 'mostrado', 5: 'mostrado', 6: 'mostrado'}},
              25: {1: {1: 'pago', 2: 'pagas', 3: 'paga', 4: 'pagamos', 5: 'pagáis', 6: 'pagan'},
                  2: {1: 'pagué', 2: 'pagaste', 3: 'pagó', 4: 'pagamos', 5: 'pagasteis', 6: 'pagaron'},
                  3: {1: 'pagaba', 2: 'pagabas', 3: 'pagaba', 4: 'pagábamos', 5: 'pagabais', 6: 'pagaban'},
                  4: {1: 'pagaré', 2: 'pagarás', 3: 'pagará', 4: 'pagaremos', 5: 'pagaréis', 6: 'pagarán'},
                  5: {1: 'pagaría', 2: 'pagarías', 3: 'pagaría', 4: 'pagaríamos', 5: 'pagaríais', 6: 'pagarían'},
                  6: {1: 'pagando', 2: 'pagando', 3: 'pagando', 4: 'pagando', 5: 'pagando', 6: 'pagando'},
                  7: {1: 'pagado/pago', 2: 'pagado/pago', 3: 'pagado/pago', 4: 'pagado/pago', 5: 'pagado/pago', 6: 'pagado/pago'}},
              26: {1: {1: 'entrego', 2: 'entregas', 3: 'entrega', 4: 'entregamos', 5: 'entregáis', 6: 'entregan'},
                  2: {1: 'entregué', 2: 'entregaste', 3: 'entregó', 4: 'entregamos', 5: 'entregasteis', 6: 'entregaron'},
                  3: {1: 'entregaba', 2: 'entregabas', 3: 'entregaba', 4: 'entregábamos', 5: 'entregabais', 6: 'entregaban'},
                  4: {1: 'entregaré', 2: 'entregarás', 3: 'entregará', 4: 'entregaremos', 5: 'entregaréis', 6: 'entregarán'},
                  5: {1: 'entregaría', 2: 'entregarías', 3: 'entregaría', 4: 'entregaríamos', 5: 'entregaríais', 6: 'entregarían'},
                  6: {1: 'entregando', 2: 'entregando', 3: 'entregando', 4: 'entregando', 5: 'entregando', 6: 'entregando'},
                  7: {1: 'entregado', 2: 'entregado', 3: 'entregado', 4: 'entregado', 5: 'entregado', 6: 'entregado'}},
              27: {1: {1: 'pego', 2: 'pegas', 3: 'pega', 4: 'pegamos', 5: 'pegáis', 6: 'pegan'},
                  2: {1: 'pegué', 2: 'pegaste', 3: 'pegó', 4: 'pegamos', 5: 'pegasteis', 6: 'pegaron'},
                  3: {1: 'pegaba', 2: 'pegabas', 3: 'pegaba', 4: 'pegábamos', 5: 'pegabais', 6: 'pegaban'},
                  4: {1: 'pegaré', 2: 'pegarás', 3: 'pegará', 4: 'pegaremos', 5: 'pegaréis', 6: 'pegarán'},
                  5: {1: 'pegaría', 2: 'pegarías', 3: 'pegaría', 4: 'pegaríamos', 5: 'pegaríais', 6: 'pegarían'},
                  6: {1: 'pegando', 2: 'pegando', 3: 'pegando', 4: 'pegando', 5: 'pegando', 6: 'pegando'},
                  7: {1: 'pegado', 2: 'pegado', 3: 'pegado', 4: 'pegado', 5: 'pegado', 6: 'pegado'}},
              28: {1: {1: 'soy', 2: 'eres', 3: 'es', 4: 'somos', 5: 'sois', 6: 'son'},
                  2: {1: 'fui', 2: 'fuiste', 3: 'fue', 4: 'fuimos', 5: 'fuisteis', 6: 'fueron'},
                  3: {1: 'ero', 2: 'eras', 3: 'era', 4: 'éramos', 5: 'erais', 6: 'eran'},
                  4: {1: 'seré', 2: 'serás', 3: 'será', 4: 'seremos', 5: 'seréis', 6: 'serán'},
                  5: {1: 'sería', 2: 'serías', 3: 'sería', 4: 'seríamos', 5: 'seríais', 6: 'serían'},
                  6: {1: 'siendo', 2: 'siendo', 3: 'siendo', 4: 'siendo', 5: 'siendo', 6: 'siendo'},
                  7: {1: 'sido', 2: 'sido', 3: 'sido', 4: 'sido', 5: 'sido', 6: 'sido'}},
              29: {1: {1: 'pongo', 2: 'pones', 3: 'pone', 4: 'ponemos', 5: 'ponéis', 6: 'ponen'},
                  2: {1: 'puse', 2: 'pusiste', 3: 'puso', 4: 'pusimos', 5: 'pusisteis', 6: 'pusieron'},
                  3: {1: 'ponía', 2: 'ponías', 3: 'ponía', 4: 'poníamos', 5: 'poníais', 6: 'ponían'},
                  4: {1: 'pondré', 2: 'pondrás', 3: 'pondrá', 4: 'pondremos', 5: 'pondréis', 6: 'pondrán'},
                  5: {1: 'pondría', 2: 'pondrías', 3: 'pondría', 4: 'pondríamos', 5: 'pondríais', 6: 'pondrían'},
                  6: {1: 'poniendo', 2: 'poniendo', 3: 'poniendo', 4: 'poniendo', 5: 'poniendo', 6: 'poniendo'},
                  7: {1: 'puesto', 2: 'puesto', 3: 'puesto', 4: 'puesto', 5: 'puesto', 6: 'puesto'}},
              30: {1: {1: 'puedo', 2: 'puedes', 3: 'puede', 4: 'podemos', 5: 'podéis', 6: 'pueden'},
                  2: {1: 'pude', 2: 'pudiste', 3: 'pudo', 4: 'pudimos', 5: 'pudisteis', 6: 'pudieron'},
                  3: {1: 'podía', 2: 'podías', 3: 'podía', 4: 'podíamos', 5: 'podíais', 6: 'podían'},
                  4: {1: 'podré', 2: 'podrás', 3: 'podrá', 4: 'podremos', 5: 'podréis', 6: 'podrán'},
                  5: {1: 'podría', 2: 'podrías', 3: 'podría', 4: 'podríamos', 5: 'podríais', 6: 'podrían'},
                  6: {1: 'pudiendo', 2: 'pudiendo', 3: 'pudiendo', 4: 'pudiendo', 5: 'pudiendo', 6: 'pudiendo'},
                  7: {1: 'podido', 2: 'podido', 3: 'podido', 4: 'podido', 5: 'podido', 6: 'podido'}},
              31: {1: {1: 'digo', 2: 'dices', 3: 'dice', 4: 'decimos', 5: 'decís', 6: 'dicen'},
                  2: {1: 'dije', 2: 'dijiste', 3: 'dijo', 4: 'dijimos', 5: 'dijisteis', 6: 'dijieron'},
                  3: {1: 'decía', 2: 'decías', 3: 'decía', 4: 'decíamos', 5: 'decíais', 6: 'decían'},
                  4: {1: 'diré', 2: 'dirás', 3: 'dirá', 4: 'diremos', 5: 'diréis', 6: 'dirán'},
                  5: {1: 'diría', 2: 'dirías', 3: 'diría', 4: 'diríamos', 5: 'diríais', 6: 'dirían'},
                  6: {1: 'diciendo', 2: 'diciendo', 3: 'diciendo', 4: 'diciendo', 5: 'diciendo', 6: 'diciendo'},
                  7: {1: 'dicho', 2: 'dicho', 3: 'dicho', 4: 'dicho', 5: 'dicho', 6: 'dicho'}},
              32: {1: {1: 'conozco', 2: 'conoces', 3: 'conoce', 4: 'conocimos', 5: 'conocéis', 6: 'conocen'},
                  2: {1: 'conocí', 2: 'conociste', 3: 'conoció', 4: 'conocimos', 5: 'conocisteis', 6: 'conocieron'},
                  3: {1: 'conocía', 2: 'conocías', 3: 'conocía', 4: 'conocíamos', 5: 'conocíais', 6: 'conocían'},
                  4: {1: 'conoceré', 2: 'conocerás', 3: 'conocerá', 4: 'conoceremos', 5: 'conoceréis', 6: 'conocerán'},
                  5: {1: 'conocería', 2: 'conocerías', 3: 'conocería', 4: 'conoceríamos', 5: 'conoceríais', 6: 'conocerían'},
                  6: {1: 'conociendo', 2: 'conociendo', 3: 'conociendo', 4: 'conociendo', 5: 'conociendo', 6: 'conociendo'},
                  7: {1: 'conocido', 2: 'conocido', 3: 'conocido', 4: 'conocido', 5: 'conocido', 6: 'conocido'}},
              33: {1: {1: 'estoy', 2: 'estás', 3: 'está', 4: 'estamos', 5: 'estáis', 6: 'están'},
                  2: {1: 'estuve', 2: 'estuviste', 3: 'estuvo', 4: 'estuvimos', 5: 'estuvisteis', 6: 'estuvieron'},
                  3: {1: 'estaba', 2: 'estabas', 3: 'estaba', 4: 'estábamos', 5: 'estabais', 6: 'estaban'},
                  4: {1: 'estaré', 2: 'estarás', 3: 'estará', 4: 'estaremos', 5: 'estaréis', 6: 'estarán'},
                  5: {1: 'estaría', 2: 'estarías', 3: 'estaría', 4: 'estaríamos', 5: 'estaríais', 6: 'estarían'},
                  6: {1: 'estando', 2: 'estando', 3: 'estando', 4: 'estando', 5: 'estando', 6: 'estando'},
                  7: {1: 'estado', 2: 'estado', 3: 'estado', 4: 'estado', 5: 'estado', 6: 'estado'}},
              34: {1: {1: 'hago', 2: 'haces', 3: 'hace', 4: 'hacemos', 5: 'hacéis', 6: 'hacen'},
                  2: {1: 'hice', 2: 'hiciste', 3: 'hizo', 4: 'hicimos', 5: 'hicisteis', 6: 'hicieron'},
                  3: {1: 'hacía', 2: 'hacías', 3: 'hacía', 4: 'hacíamos', 5: 'hacíais', 6: 'hacían'},
                  4: {1: 'haré', 2: 'harás', 3: 'hará', 4: 'haremos', 5: 'haréis', 6: 'harán'},
                  5: {1: 'haría', 2: 'harías', 3: 'haría', 4: 'haríamos', 5: 'haríais', 6: 'harían'},
                  6: {1: 'haciendo', 2: 'haciendo', 3: 'haciendo', 4: 'haciendo', 5: 'haciendo', 6: 'haciendo'},
                  7: {1: 'hecho', 2: 'hecho', 3: 'hecho', 4: 'hecho', 5: 'hecho', 6: 'hecho'}},
              35: {1: {1: 'quiero', 2: 'quieres', 3: 'quiere', 4: 'queremos', 5: 'queréis', 6: 'quieren'},
                  2: {1: 'quise', 2: 'quisiste', 3: 'quiso', 4: 'quisimos', 5: 'quisisteis', 6: 'quisieron'},
                  3: {1: 'quería', 2: 'querías', 3: 'quería', 4: 'queríamos', 5: 'queríais', 6: 'querbían'},
                  4: {1: 'querré', 2: 'querrás', 3: 'querrá', 4: 'querremos', 5: 'querréis', 6: 'querrán'},
                  5: {1: 'querría', 2: 'querrías', 3: 'querría', 4: 'querríamos', 5: 'querríais', 6: 'querrían'},
                  6: {1: 'queriendo', 2: 'queriendo', 3: 'queriendo', 4: 'queriendo', 5: 'queriendo', 6: 'queriendo'},
                  7: {1: 'querido', 2: 'querido', 3: 'querido', 4: 'querido', 5: 'querido', 6: 'querido'}},
              36: {1: {1: 'encuentro', 2: 'encuentras', 3: 'encuentra', 4: 'encontramos', 5: 'encontráis', 6: 'encuentran'},
                  2: {1: 'encontré', 2: 'encontraste', 3: 'encontró', 4: 'encontramos', 5: 'encontrasteis', 6: 'encontraron'},
                  3: {1: 'encontraba', 2: 'encontrabas', 3: 'encontraba', 4: 'encontrábamos', 5: 'encontrabais', 6: 'encontraban'},
                  4: {1: 'encontraré', 2: 'encontrarás', 3: 'encontrará', 4: 'encontraremos', 5: 'encontraréis', 6: 'encontrarán'},
                  5: {1: 'encontraría', 2: 'encontrarías', 3: 'encontraría', 4: 'encontraríamos', 5: 'encontraríais', 6: 'encontrarían'},
                  6: {1: 'encontrando', 2: 'encontrando', 3: 'encontrando', 4: 'encontrando', 5: 'encontrando', 6: 'encontrando'},
                  7: {1: 'encontrado', 2: 'encontrado', 3: 'encontrado', 4: 'encontrado', 5: 'encontrado', 6: 'encontrado'}},
              37: {1: {1: 'parezco', 2: 'pareces', 3: 'parece', 4: 'parecemos', 5: 'parecéis', 6: 'parecen'},
                  2: {1: 'parecí', 2: 'pareciste', 3: 'pareció', 4: 'parecimos', 5: 'parecisteis', 6: 'parecieron'},
                  3: {1: 'parecía', 2: 'parecías', 3: 'parecía', 4: 'parecíamos', 5: 'parecíais', 6: 'parecían'},
                  4: {1: 'pareceré', 2: 'parecerás', 3: 'parecerá', 4: 'pareceremos', 5: 'pareceréis', 6: 'parecerán'},
                  5: {1: 'parecería', 2: 'parecerías', 3: 'parecería', 4: 'pareceríamos', 5: 'pareceríais', 6: 'parecerían'},
                  6: {1: 'pareciendo', 2: 'pareciendo', 3: 'pareciendo', 4: 'pareciendo', 5: 'pareciendo', 6: 'pareciendo'},
                  7: {1: 'parecido', 2: 'parecido', 3: 'parecido', 4: 'parecido', 5: 'parecido', 6: 'parecido'}},
              38: {1: {1: 'voy', 2: 'vas', 3: 'va', 4: 'vamos', 5: 'vais', 6: 'van'},
                  2: {1: 'fui', 2: 'fuiste', 3: 'fue', 4: 'fuimos', 5: 'fuisteis', 6: 'fueron'},
                  3: {1: 'iba', 2: 'ibas', 3: 'iba', 4: 'ibamos', 5: 'ibais', 6: 'iban'},
                  4: {1: 'iré', 2: 'irás', 3: 'irá', 4: 'iremos', 5: 'iréis', 6: 'irán'},
                  5: {1: 'iría', 2: 'irías', 3: 'iría', 4: 'iríamos', 5: 'iríais', 6: 'irían'},
                  6: {1: 'yendo', 2: 'yendo', 3: 'yendo', 4: 'yendo', 5: 'yendo', 6: 'yendo'},
                  7: {1: 'ido', 2: 'ido', 3: 'ido', 4: 'ido', 5: 'ido', 6: 'ido'}},
              39: {1: {1: 'tengo', 2: 'tienes', 3: 'tiene', 4: 'tenemos', 5: 'tenéis', 6: 'tienen'},
                  2: {1: 'tuve', 2: 'tuviste', 3: 'tuvo', 4: 'tuvimos', 5: 'tuvisteis', 6: 'tuvieron'},
                  3: {1: 'tenía', 2: 'tenías', 3: 'tenía', 4: 'teníamos', 5: 'teníais', 6: 'tenían'},
                  4: {1: 'tendré', 2: 'tendrás', 3: 'tendrá', 4: 'tendremos', 5: 'tendréis', 6: 'tendrán'},
                  5: {1: 'tendría', 2: 'tendrías', 3: 'tendría', 4: 'tendríamos', 5: 'tendríais', 6: 'tendrían'},
                  6: {1: 'teniendo', 2: 'teniendo', 3: 'teniendo', 4: 'teniendo', 5: 'teniendo', 6: 'teniendo'},
                  7: {1: 'tenido', 2: 'tenido', 3: 'tenido', 4: 'tenido', 5: 'tenido', 6: 'tenido'}},
              40: {1: {1: 'pienso', 2: 'piensas', 3: 'piensa', 4: 'pensamos', 5: 'pensáis', 6: 'piensan'},
                  2: {1: 'pensé', 2: 'pensaste', 3: 'pensó', 4: 'pensamos', 5: 'pensasteis', 6: 'pensaron'},
                  3: {1: 'pensaba', 2: 'pensabas', 3: 'pensaba', 4: 'pensábamos', 5: 'pensabais', 6: 'pensaban'},
                  4: {1: 'pensaré', 2: 'pensarás', 3: 'pensará', 4: 'pensaremos', 5: 'pensaréis', 6: 'pensarán'},
                  5: {1: 'pensaría', 2: 'pensarías', 3: 'pensaría', 4: 'pensaríamos', 5: 'pensaríais', 6: 'pensarían'},
                  6: {1: 'pensando', 2: 'pensando', 3: 'pensando', 4: 'pensando', 5: 'pensando', 6: 'pensando'},
                  7: {1: 'pensado', 2: 'pensado', 3: 'pensado', 4: 'pensado', 5: 'pensado', 6: 'pensado'}},
              41: {1: {1: 'cierro', 2: 'cierras', 3: 'cierra', 4: 'cerramos', 5: 'cerráis', 6: 'cierran'},
                  2: {1: 'cerré', 2: 'cerraste', 3: 'cerró', 4: 'cerramos', 5: 'cerrasteis', 6: 'cerraron'},
                  3: {1: 'cerraba', 2: 'cerrabas', 3: 'cerraba', 4: 'cerrábamos', 5: 'cerrabais', 6: 'cerraban'},
                  4: {1: 'cerraré', 2: 'cerrarás', 3: 'cerrará', 4: 'cerraremos', 5: 'cerraréis', 6: 'cerrarán'},
                  5: {1: 'cerraría', 2: 'cerrarías', 3: 'cerraría', 4: 'cerraríamos', 5: 'cerraríais', 6: 'cerrarían'},
                  6: {1: 'cerrando', 2: 'cerrando', 3: 'cerrando', 4: 'cerrando', 5: 'cerrando', 6: 'cerrando'},
                  7: {1: 'cerrado', 2: 'cerrado', 3: 'cerrado', 4: 'cerrado', 5: 'cerrado', 6: 'cerrado'}},
              42: {1: {1: 'acuesto', 2: 'acuestas', 3: 'acuesta', 4: 'acostamos', 5: 'acostáis', 6: 'acuestan'},
                  2: {1: 'acosté', 2: 'acostaste', 3: 'acostó', 4: 'acostamos', 5: 'acostasteis', 6: 'acostaron'},
                  3: {1: 'acostaba', 2: 'acostabas', 3: 'acostaba', 4: 'acostábamos', 5: 'acostabais', 6: 'acostaban'},
                  4: {1: 'acostaré', 2: 'acostarás', 3: 'acostará', 4: 'acostaremos', 5: 'acostaréis', 6: 'acostarán'},
                  5: {1: 'acostaría', 2: 'acostarías', 3: 'acostaría', 4: 'acostaríamos', 5: 'acostaríais', 6: 'acostarían'},
                  6: {1: 'acostando', 2: 'acostando', 3: 'acostando', 4: 'acostando', 5: 'acostando', 6: 'acostando'},
                  7: {1: 'acostado', 2: 'acostado', 3: 'acostado', 4: 'acostado', 5: 'acostado', 6: 'acostado'}},
              43: {1: {1: 'doy', 2: 'das', 3: 'da', 4: 'damos', 5: 'dais', 6: 'dan'},
                  2: {1: 'di', 2: 'diste', 3: 'dio', 4: 'dimos', 5: 'disteis', 6: 'dieron'},
                  3: {1: 'daba', 2: 'dabas', 3: 'daba', 4: 'dábamos', 5: 'dabais', 6: 'daban'},
                  4: {1: 'daré', 2: 'darás', 3: 'dará', 4: 'daremos', 5: 'daréis', 6: 'darán'},
                  5: {1: 'daría', 2: 'darías', 3: 'daría', 4: 'daríamos', 5: 'daríais', 6: 'darían'},
                  6: {1: 'dando', 2: 'dando', 3: 'dando', 4: 'dando', 5: 'dando', 6: 'dando'},
                  7: {1: 'dado', 2: 'dado', 3: 'dado', 4: 'dado', 5: 'dado', 6: 'dado'}},
              44: {1: {1: 'veo', 2: 'ves', 3: 've', 4: 'vemos', 5: 'veis', 6: 'ven'},
                  2: {1: 'vi', 2: 'viste', 3: 'vio', 4: 'vimos', 5: 'visteis', 6: 'vieron'},
                  3: {1: 'veía', 2: 'veías', 3: 'veía', 4: 'veíamos', 5: 'veíais', 6: 'veían'},
                  4: {1: 'veré', 2: 'verás', 3: 'verá', 4: 'veremos', 5: 'veréis', 6: 'verán'},
                  5: {1: 'vería', 2: 'verías', 3: 'vería', 4: 'veríamos', 5: 'veríais', 6: 'verían'},
                  6: {1: 'viendo', 2: 'viendo', 3: 'viendo', 4: 'viendo', 5: 'viendo', 6: 'viendo'},
                  7: {1: 'visto', 2: 'visto', 3: 'visto', 4: 'visto', 5: 'visto', 6: 'visto'}},
              45: {1: {1: 'vengo', 2: 'vienes', 3: 'viene', 4: 'venimos', 5: 'venís', 6: 'vienen'},
                  2: {1: 'vine', 2: 'viniste', 3: 'vino', 4: 'vinimos', 5: 'vinisteis', 6: 'vinieron'},
                  3: {1: 'venía', 2: 'venías', 3: 'venía', 4: 'veníamos', 5: 'veníais', 6: 'venían'},
                  4: {1: 'vendré', 2: 'vendrás', 3: 'vendrá', 4: 'vendremos', 5: 'vendréis', 6: 'vendrán'},
                  5: {1: 'vendría', 2: 'vendrías', 3: 'vendría', 4: 'vendríamos', 5: 'vendríais', 6: 'vendrían'},
                  6: {1: 'viniendo', 2: 'viniendo', 3: 'viniendo', 4: 'viniendo', 5: 'viniendo', 6: 'viniendo'},
                  7: {1: 'venido', 2: 'venido', 3: 'venido', 4: 'venido', 5: 'venido', 6: 'venido'}},
              46: {1: {1: 'pierdo', 2: 'pierdes', 3: 'pierde', 4: 'perdemos', 5: 'perdéis', 6: 'pierden'},
                  2: {1: 'perdí', 2: 'perdiste', 3: 'perdió', 4: 'perdimos', 5: 'perdisteis', 6: 'perdieron'},
                  3: {1: 'perdía', 2: 'perdías', 3: 'perdía', 4: 'perdíamos', 5: 'perdíais', 6: 'perdían'},
                  4: {1: 'perderé', 2: 'perderás', 3: 'perderá', 4: 'perderemos', 5: 'perderéis', 6: 'perderán'},
                  5: {1: 'perdería', 2: 'perderías', 3: 'perdería', 4: 'perderíamos', 5: 'perderíais', 6: 'perderían'},
                  6: {1: 'perdiendo', 2: 'perdiendo', 3: 'perdiendo', 4: 'perdiendo', 5: 'perdiendo', 6: 'perdiendo'},
                  7: {1: 'perdido', 2: 'perdido', 3: 'perdido', 4: 'perdido', 5: 'perdido', 6: 'perdido'}},
              47: {1: {1: 'traigo', 2: 'traes', 3: 'trae', 4: 'traemos', 5: 'traéis', 6: 'traen'},
                  2: {1: 'traje', 2: 'trajiste', 3: 'trajo', 4: 'trajimos', 5: 'trajisteis', 6: 'trajeron'},
                  3: {1: 'traía', 2: 'traías', 3: 'traía', 4: 'traíamos', 5: 'traíais', 6: 'traían'},
                  4: {1: 'traeré', 2: 'traerás', 3: 'traerá', 4: 'traeremos', 5: 'traeréis', 6: 'traerán'},
                  5: {1: 'traería', 2: 'traerías', 3: 'traería', 4: 'traeríamos', 5: 'traeríais', 6: 'traerían'},
                  6: {1: 'trayendo', 2: 'trayendo', 3: 'trayendo', 4: 'trayendo', 5: 'trayendo', 6: 'trayendo'},
                  7: {1: 'traído', 2: 'traído', 3: 'traído', 4: 'traído', 5: 'traído', 6: 'traído'}},
              48: {1: {1: 'enciendo', 2: 'enciendes', 3: 'enciende', 4: 'encendemos', 5: 'encendéis', 6: 'encienden'},
                  2: {1: 'encendí', 2: 'encendiste', 3: 'encendió', 4: 'encendimos', 5: 'encendisteis', 6: 'encendieron'},
                  3: {1: 'encendía', 2: 'encendías', 3: 'encendía', 4: 'encendíamos', 5: 'encendíais', 6: 'encendían'},
                  4: {1: 'encenderé', 2: 'encenderás', 3: 'encenderá', 4: 'encenderemos', 5: 'encenderéis', 6: 'encenderán'},
                  5: {1: 'encendería', 2: 'encenderías', 3: 'encendería', 4: 'encenderíamos', 5: 'encenderíais', 6: 'encenderían'},
                  6: {1: 'encendiendo', 2: 'encendiendo', 3: 'encendiendo', 4: 'encendiendo', 5: 'encendiendo', 6: 'encendiendo'},
                  7: {1: 'encendido', 2: 'encendido', 3: 'encendido', 4: 'encendido', 5: 'encendido', 6: 'encendido'}},
              49: {1: {1: 'sé', 2: 'sabes', 3: 'sabe', 4: 'sabemos', 5: 'sabéis', 6: 'saben'},
                  2: {1: 'supe', 2: 'supiste', 3: 'supo', 4: 'supimos', 5: 'supisteis', 6: 'supieron'},
                  3: {1: 'sabía', 2: 'sabías', 3: 'sabía', 4: 'sabíamos', 5: 'sabíais', 6: 'sabían'},
                  4: {1: 'sabré', 2: 'sabrás', 3: 'sabrá', 4: 'sabremos', 5: 'sabréis', 6: 'sabrán'},
                  5: {1: 'sabría', 2: 'sabrías', 3: 'sabría', 4: 'sabríamos', 5: 'sabríais', 6: 'sabrían'},
                  6: {1: 'sabiendo', 2: 'sabiendo', 3: 'sabiendo', 4: 'sabiendo', 5: 'sabiendo', 6: 'sabiendo'},
                  7: {1: 'sabido', 2: 'sabido', 3: 'sabido', 4: 'sabido', 5: 'sabido', 6: 'sabido'}},
              50: {1: {1: 'duermo', 2: 'duermes', 3: 'duerme', 4: 'dormimos', 5: 'dormís', 6: 'duermen'},
                  2: {1: 'dormí', 2: 'dormiste', 3: 'durmió', 4: 'dormimos', 5: 'dormisteis', 6: 'durmieron'},
                  3: {1: 'dormía', 2: 'dormías', 3: 'dormía', 4: 'dormíamos', 5: 'dormíais', 6: 'dormían'},
                  4: {1: 'dormiré', 2: 'dormirás', 3: 'dormirá', 4: 'dormiremos', 5: 'dormiréis', 6: 'dormirán'},
                  5: {1: 'dormiría', 2: 'dormirías', 3: 'dormiría', 4: 'dormiríamos', 5: 'dormiríais', 6: 'dormirían'},
                  6: {1: 'durmiendo', 2: 'durmiendo', 3: 'durmiendo', 4: 'durmiendo', 5: 'durmiendo', 6: 'durmiendo'},
                  7: {1: 'dormido', 2: 'dormido', 3: 'dormido', 4: 'dormido', 5: 'dormido', 6: 'dormido'}},
              51: {1: {1: 'entiendo', 2: 'entiendes', 3: 'entiende', 4: 'entendemos', 5: 'entendéis', 6: 'entienden'},
                  2: {1: 'entendí', 2: 'entendiste', 3: 'entendió', 4: 'entendimos', 5: 'entendisteis', 6: 'entendieron'},
                  3: {1: 'entendía', 2: 'entendías', 3: 'entendía', 4: 'entendíamos', 5: 'entendíais', 6: 'entendían'},
                  4: {1: 'entenderé', 2: 'entenderás', 3: 'entenderá', 4: 'entenderemos', 5: 'entenderéis', 6: 'entenderán'},
                  5: {1: 'entendería', 2: 'entenderías', 3: 'entendería', 4: 'entenderíamos', 5: 'entenderíais', 6: 'entenderían'},
                  6: {1: 'entendiendo', 2: 'entendiendo', 3: 'entendiendo', 4: 'entendiendo', 5: 'entendiendo', 6: 'entendiendo'},
                  7: {1: 'entendido', 2: 'entendido', 3: 'entendido', 4: 'entendido', 5: 'entendido', 6: 'entendido'}},
              52: {1: {1: 'pido', 2: 'pides', 3: 'pide', 4: 'pedimos', 5: 'pedís', 6: 'piden'},
                  2: {1: 'pedí', 2: 'pediste', 3: 'pidió', 4: 'pedimos', 5: 'pedisteis', 6: 'pidieron'},
                  3: {1: 'pedía', 2: 'pedías', 3: 'pedía', 4: 'pedíamos', 5: 'pedíais', 6: 'pedían'},
                  4: {1: 'pediré', 2: 'pedirás', 3: 'pedirá', 4: 'pediremos', 5: 'pediréis', 6: 'pedirán'},
                  5: {1: 'pediría', 2: 'pedirías', 3: 'pediría', 4: 'pediríamos', 5: 'pediríais', 6: 'pedirían'},
                  6: {1: 'pidiendo', 2: 'pidiendo', 3: 'pidiendo', 4: 'pidiendo', 5: 'pidiendo', 6: 'pidiendo'},
                  7: {1: 'pedido', 2: 'pedido', 3: 'pedido', 4: 'pedido', 5: 'pedido', 6: 'pedido'}},
              53: {1: {1: 'prefiero', 2: 'prefieres', 3: 'prefiere', 4: 'preferimos', 5: 'preferís', 6: 'prefieren'},
                  2: {1: 'preferí', 2: 'preferiste', 3: 'prefirió', 4: 'preferimos', 5: 'preferisteis', 6: 'prefirieron'},
                  3: {1: 'prefería', 2: 'preferías', 3: 'prefería', 4: 'preferíamos', 5: 'preferíais', 6: 'preferían'},
                  4: {1: 'preferiré', 2: 'preferirás', 3: 'preferirá', 4: 'preferiremos', 5: 'preferiréis', 6: 'preferirán'},
                  5: {1: 'preferiría', 2: 'preferirías', 3: 'preferiría', 4: 'preferiríamos', 5: 'preferiríais', 6: 'preferirían'},
                  6: {1: 'prefiriendo', 2: 'prefiriendo', 3: 'prefiriendo', 4: 'prefiriendo', 5: 'prefiriendo', 6: 'prefiriendo'},
                  7: {1: 'preferido', 2: 'preferido', 3: 'preferido', 4: 'preferido', 5: 'preferido', 6: 'preferido'}},
              54: {1: {1: 'sigo', 2: 'sigues', 3: 'sigue', 4: 'seguimos', 5: 'seguís', 6: 'siguen'},
                  2: {1: 'seguí', 2: 'seguiste', 3: 'siguió', 4: 'seguimos', 5: 'seguisteis', 6: 'siguieron'},
                  3: {1: 'seguía', 2: 'seguías', 3: 'seguía', 4: 'seguíamos', 5: 'seguíais', 6: 'seguían'},
                  4: {1: 'seguiré', 2: 'seguirás', 3: 'seguirá', 4: 'seguiremos', 5: 'seguiréis', 6: 'seguirán'},
                  5: {1: 'seguiría', 2: 'seguirías', 3: 'seguiría', 4: 'seguiríamos', 5: 'seguiríais', 6: 'seguirían'},
                  6: {1: 'siguiendo', 2: 'siguiendo', 3: 'siguiendo', 4: 'siguiendo', 5: 'siguiendo', 6: 'siguiendo'},
                  7: {1: 'seguido', 2: 'seguido', 3: 'seguido', 4: 'seguido', 5: 'seguido', 6: 'seguido'}},
              55: {1: {1: 'siento', 2: 'sientes', 3: 'siente', 4: 'sentimos', 5: 'sentís', 6: 'sienten'},
                  2: {1: 'sentí', 2: 'sentiste', 3: 'sintió', 4: 'sentimos', 5: 'sentisteis', 6: 'sintieron'},
                  3: {1: 'sentía', 2: 'sentías', 3: 'sentía', 4: 'sentíamos', 5: 'sentíais', 6: 'sentían'},
                  4: {1: 'sentiré', 2: 'sentirás', 3: 'sentirá', 4: 'sentiremos', 5: 'sentiréis', 6: 'sentirán'},
                  5: {1: 'sentiría', 2: 'sentirías', 3: 'sentiría', 4: 'sentiríamos', 5: 'sentiríais', 6: 'sentirían'},
                  6: {1: 'sintiendo', 2: 'sintiendo', 3: 'sintiendo', 4: 'sintiendo', 5: 'sintiendo', 6: 'sintiendo'},
                  7: {1: 'sentido', 2: 'sentido', 3: 'sentido', 4: 'sentido', 5: 'sentido', 6: 'sentido'}},
              56: {1: {1: 'siento', 2: 'sientas', 3: 'sienta', 4: 'sentamos', 5: 'sentáis', 6: 'sientan'},
                  2: {1: 'senté', 2: 'sentaste', 3: 'sentó', 4: 'sentamos', 5: 'sentasteis', 6: 'sentaron'},
                  3: {1: 'sentaba', 2: 'sentabas', 3: 'sentaba', 4: 'sentábamos', 5: 'sentabais', 6: 'sentaban'},
                  4: {1: 'sentaré', 2: 'sentarás', 3: 'sentará', 4: 'sentaremos', 5: 'sentaréis', 6: 'sentarán'},
                  5: {1: 'sentaría', 2: 'sentarías', 3: 'sentaría', 4: 'sentaríamos', 5: 'sentaríais', 6: 'sentarían'},
                  6: {1: 'sentando', 2: 'sentando', 3: 'sentando', 4: 'sentando', 5: 'sentando', 6: 'sentando'},
                  7: {1: 'sentado', 2: 'sentado', 3: 'sentado', 4: 'sentado', 5: 'sentado', 6: 'sentado'}},
              57: {1: {1: 'huelo', 2: 'hueles', 3: 'huele', 4: 'olemos', 5: 'oléis', 6: 'huelen'},
                  2: {1: 'olí', 2: 'oliste', 3: 'olió', 4: 'olimos', 5: 'olisteis', 6: 'olieron'},
                  3: {1: 'olía', 2: 'olías', 3: 'olía', 4: 'olíamos', 5: 'olíais', 6: 'olían'},
                  4: {1: 'oleré', 2: 'olerás', 3: 'olerá', 4: 'oleremos', 5: 'oleréis', 6: 'olerán'},
                  5: {1: 'olería', 2: 'olerías', 3: 'olería', 4: 'oleríamos', 5: 'oleríais', 6: 'olerían'},
                  6: {1: 'oliendo', 2: 'oliendo', 3: 'oliendo', 4: 'oliendo', 5: 'oliendo', 6: 'oliendo'},
                  7: {1: 'olido', 2: 'olido', 3: 'olido', 4: 'olido', 5: 'olido', 6: 'olido'}},
              58: {1: {1: 'practico', 2: 'practicas', 3: 'practica', 4: 'practicamos', 5: 'practicáis', 6: 'practican'},
                  2: {1: 'practiqué', 2: 'practicaste', 3: 'practicó', 4: 'practicamos', 5: 'practicasteis', 6: 'practicaron'},
                  3: {1: 'practicaba', 2: 'practicabas', 3: 'practicaba', 4: 'practicábamos', 5: 'practicabais', 6: 'practicaban'},
                  4: {1: 'practicaré', 2: 'practicarás', 3: 'practicará', 4: 'practicaremos', 5: 'practicaréis', 6: 'practicarán'},
                  5: {1: 'practicaría', 2: 'practicarías', 3: 'practicaría', 4: 'practicaríamos', 5: 'practicaríais', 6: 'practicarían'},
                  6: {1: 'practicando', 2: 'practicando', 3: 'practicando', 4: 'practicando', 5: 'practicando', 6: 'practicando'},
                  7: {1: 'practicado', 2: 'practicado', 3: 'practicado', 4: 'practicado', 5: 'practicado', 6: 'practicado'}},
              59: {1: {1: 'amo', 2: 'amas', 3: 'ama', 4: 'amamos', 5: 'amáis', 6: 'aman'},
                  2: {1: 'amé', 2: 'amaste', 3: 'amó', 4: 'amamos', 5: 'amasteis', 6: 'amaron'},
                  3: {1: 'amaba', 2: 'amabas', 3: 'amaba', 4: 'amábamos', 5: 'amabais', 6: 'amaban'},
                  4: {1: 'amaré', 2: 'amarás', 3: 'amará', 4: 'amaremos', 5: 'amaréis', 6: 'amarán'},
                  5: {1: 'amaría', 2: 'amarías', 3: 'amaría', 4: 'amaríamos', 5: 'amaríais', 6: 'amarían'},
                  6: {1: 'amando', 2: 'amando', 3: 'amando', 4: 'amando', 5: 'amando', 6: 'amando'},
                  7: {1: 'amado', 2: 'amado', 3: 'amado', 4: 'amado', 5: 'amado', 6: 'amado'}},
              60: {1: {1: 'como', 2: 'comes', 3: 'come', 4: 'comemos', 5: 'coméis', 6: 'comen'},
                  2: {1: 'comí', 2: 'comiste', 3: 'comió', 4: 'comimos', 5: 'comisteis', 6: 'comieron'},
                  3: {1: 'comía', 2: 'comías', 3: 'comía', 4: 'comíamos', 5: 'comíais', 6: 'comían'},
                  4: {1: 'comeré', 2: 'comerás', 3: 'comerá', 4: 'comeremos', 5: 'comeréis', 6: 'comerán'},
                  5: {1: 'comería', 2: 'comerías', 3: 'comería', 4: 'comeríamos', 5: 'comeríais', 6: 'comerían'},
                  6: {1: 'comiendo', 2: 'comiendo', 3: 'comiendo', 4: 'comiendo', 5: 'comiendo', 6: 'comiendo'},
                  7: {1: 'comido', 2: 'comido', 3: 'comido', 4: 'comido', 5: 'comido', 6: 'comido'}},
              61: {1: {1: 'vivo', 2: 'vives', 3: 'vive', 4: 'vivimos', 5: 'vivís', 6: 'viven'},
                  2: {1: 'viví', 2: 'viviste', 3: 'vivió', 4: 'vivimos', 5: 'vivisteis', 6: 'vivieron'},
                  3: {1: 'vivía', 2: 'vivías', 3: 'vivía', 4: 'vivíamos', 5: 'vivíais', 6: 'vivían'},
                  4: {1: 'viviré', 2: 'vivirás', 3: 'vivirá', 4: 'viviremos', 5: 'viviréis', 6: 'vivirán'},
                  5: {1: 'viviría', 2: 'vivirías', 3: 'viviría', 4: 'viviríamos', 5: 'viviríais', 6: 'vivirían'},
                  6: {1: 'viviendo', 2: 'viviendo', 3: 'viviendo', 4: 'viviendo', 5: 'viviendo', 6: 'viviendo'},
                  7: {1: 'vivido', 2: 'vivido', 3: 'vivido', 4: 'vivido', 5: 'vivido', 6: 'vivido'}},
              62: {1: {1: 'bailo', 2: 'bailas', 3: 'baila', 4: 'bailamos', 5: 'bailáis', 6: 'bailan'},
                  2: {1: 'bailé', 2: 'bailaste', 3: 'bailó', 4: 'bailamos', 5: 'bailasteis', 6: 'bailaron'},
                  3: {1: 'bailaba', 2: 'bailabas', 3: 'bailaba', 4: 'bailábamos', 5: 'bailabais', 6: 'bailaban'},
                  4: {1: 'bailaré', 2: 'bailarás', 3: 'bailará', 4: 'bailaremos', 5: 'bailaréis', 6: 'bailarán'},
                  5: {1: 'bailaría', 2: 'bailarías', 3: 'bailaría', 4: 'bailaríamos', 5: 'bailaríais', 6: 'bailarían'},
                  6: {1: 'bailando', 2: 'bailando', 3: 'bailando', 4: 'bailando', 5: 'bailando', 6: 'bailando'},
                  7: {1: 'bailado', 2: 'bailado', 3: 'bailado', 4: 'bailado', 5: 'bailado', 6: 'bailado'}},
              63: {1: {1: 'canto', 2: 'cantas', 3: 'canta', 4: 'cantamos', 5: 'cantáis', 6: 'cantan'},
                  2: {1: 'canté', 2: 'cantaste', 3: 'cantó', 4: 'cantamos', 5: 'cantasteis', 6: 'cantaron'},
                  3: {1: 'cantaba', 2: 'cantabas', 3: 'cantaba', 4: 'cantábamos', 5: 'cantabais', 6: 'cantaban'},
                  4: {1: 'cantaré', 2: 'cantarás', 3: 'cantará', 4: 'cantaremos', 5: 'cantaréis', 6: 'cantarán'},
                  5: {1: 'cantaría', 2: 'cantarías', 3: 'cantaría', 4: 'cantaríamos', 5: 'cantaríais', 6: 'cantarían'},
                  6: {1: 'cantando', 2: 'cantando', 3: 'cantando', 4: 'cantando', 5: 'cantando', 6: 'cantando'},
                  7: {1: 'cantado', 2: 'cantado', 3: 'cantado', 4: 'cantado', 5: 'cantado', 6: 'cantado'}},
              64: {1: {1: 'compro', 2: 'compras', 3: 'compra', 4: 'compramos', 5: 'compráis', 6: 'compran'},
                  2: {1: 'compré', 2: 'compraste', 3: 'compró', 4: 'compramos', 5: 'comprasteis', 6: 'compraron'},
                  3: {1: 'compraba', 2: 'comprabas', 3: 'compraba', 4: 'comprábamos', 5: 'comprabais', 6: 'compraban'},
                  4: {1: 'compraré', 2: 'comprarás', 3: 'comprará', 4: 'compraremos', 5: 'compraréis', 6: 'comprarán'},
                  5: {1: 'compraría', 2: 'comprarías', 3: 'compraría', 4: 'compraríamos', 5: 'compraríais', 6: 'comprarían'},
                  6: {1: 'comprando', 2: 'comprando', 3: 'comprando', 4: 'comprando', 5: 'comprando', 6: 'comprando'},
                  7: {1: 'comprado', 2: 'comprado', 3: 'comprado', 4: 'comprado', 5: 'comprado', 6: 'comprado'}},
              65: {1: {1: 'trabajo', 2: 'trabajas', 3: 'trabaja', 4: 'trabajamos', 5: 'trabajáis', 6: 'trabajan'},
                  2: {1: 'trabajé', 2: 'trabajaste', 3: 'trabajó', 4: 'trabajamos', 5: 'trabajasteis', 6: 'trabajaron'},
                  3: {1: 'trabajaba', 2: 'trabajabas', 3: 'trabajaba', 4: 'trabajábamos', 5: 'trabajabais', 6: 'trabajaban'},
                  4: {1: 'trabajaré', 2: 'trabajarás', 3: 'trabajará', 4: 'trabajaremos', 5: 'trabajaréis', 6: 'trabajarán'},
                  5: {1: 'trabajaría', 2: 'trabajarías', 3: 'trabajaría', 4: 'trabajaríamos', 5: 'trabajaríais', 6: 'trabajarían'},
                  6: {1: 'trabajando', 2: 'trabajando', 3: 'trabajando', 4: 'trabajando', 5: 'trabajando', 6: 'trabajando'},
                  7: {1: 'trabajado', 2: 'trabajado', 3: 'trabajado', 4: 'trabajado', 5: 'trabajado', 6: 'trabajado'}},
              66: {1: {1: 'tomo', 2: 'tomas', 3: 'toma', 4: 'tomamos', 5: 'tomáis', 6: 'toman'},
                  2: {1: 'tomé', 2: 'tomaste', 3: 'tomó', 4: 'tomamos', 5: 'tomasteis', 6: 'tomaron'},
                  3: {1: 'tomaba', 2: 'tomabas', 3: 'tomaba', 4: 'tomábamos', 5: 'tomabais', 6: 'tomaban'},
                  4: {1: 'tomaré', 2: 'tomarás', 3: 'tomará', 4: 'tomaremos', 5: 'tomaréis', 6: 'tomarán'},
                  5: {1: 'tomaría', 2: 'tomarías', 3: 'tomaría', 4: 'tomaríamos', 5: 'tomaríais', 6: 'tomarían'},
                  6: {1: 'tomando', 2: 'tomando', 3: 'tomando', 4: 'tomando', 5: 'tomando', 6: 'tomando'},
                  7: {1: 'tomado', 2: 'tomado', 3: 'tomado', 4: 'tomado', 5: 'tomado', 6: 'tomado'}},
              67: {1: {1: 'cocino', 2: 'cocinas', 3: 'cocina', 4: 'cocinamos', 5: 'cocináis', 6: 'cocinan'},
                  2: {1: 'cociné', 2: 'cocinaste', 3: 'cocinó', 4: 'cocinamos', 5: 'cocinasteis', 6: 'cocinaron'},
                  3: {1: 'cocinaba', 2: 'cocinabas', 3: 'cocinaba', 4: 'cocinábamos', 5: 'cocinabais', 6: 'cocinaban'},
                  4: {1: 'cocinaré', 2: 'cocinarás', 3: 'cocinará', 4: 'cocinaremos', 5: 'cocinaréis', 6: 'cocinarán'},
                  5: {1: 'cocinaría', 2: 'cocinarías', 3: 'cocinaría', 4: 'cocinaríamos', 5: 'cocinaríais', 6: 'cocinarían'},
                  6: {1: 'cocinando', 2: 'cocinando', 3: 'cocinando', 4: 'cocinando', 5: 'cocinando', 6: 'cocinando'},
                  7: {1: 'cocinado', 2: 'cocinado', 3: 'cocinado', 4: 'cocinado', 5: 'cocinado', 6: 'cocinado'}},
              68: {1: {1: 'enseño', 2: 'enseñas', 3: 'enseña', 4: 'enseñamos', 5: 'enseñáis', 6: 'enseñan'},
                  2: {1: 'enseñé', 2: 'enseñaste', 3: 'enseñó', 4: 'enseñamos', 5: 'enseñasteis', 6: 'enseñaron'},
                  3: {1: 'enseñaba', 2: 'enseñabas', 3: 'enseñaba', 4: 'enseñábamos', 5: 'enseñabais', 6: 'enseñaban'},
                  4: {1: 'enseñaré', 2: 'enseñarás', 3: 'enseñará', 4: 'enseñaremos', 5: 'enseñaréis', 6: 'enseñarán'},
                  5: {1: 'enseñaría', 2: 'enseñarías', 3: 'enseñaría', 4: 'enseñaríamos', 5: 'enseñaríais', 6: 'enseñarían'},
                  6: {1: 'enseñando', 2: 'enseñando', 3: 'enseñando', 4: 'enseñando', 5: 'enseñando', 6: 'enseñando'},
                  7: {1: 'enseñado', 2: 'enseñado', 3: 'enseñado', 4: 'enseñado', 5: 'enseñado', 6: 'enseñado'}},
              69: {1: {1: 'llamo', 2: 'llamas', 3: 'llama', 4: 'llamamos', 5: 'llamáis', 6: 'llaman'},
                  2: {1: 'llamé', 2: 'llamaste', 3: 'llamó', 4: 'llamamos', 5: 'llamasteis', 6: 'llamaron'},
                  3: {1: 'llamaba', 2: 'llamabas', 3: 'llamaba', 4: 'llamábamos', 5: 'llamabais', 6: 'llamaban'},
                  4: {1: 'llamaré', 2: 'llamarás', 3: 'llamará', 4: 'llamaremos', 5: 'llamaréis', 6: 'llamarán'},
                  5: {1: 'llamaría', 2: 'llamarías', 3: 'llamaría', 4: 'llamaríamos', 5: 'llamaríais', 6: 'llamarían'},
                  6: {1: 'llamando', 2: 'llamando', 3: 'llamando', 4: 'llamando', 5: 'llamando', 6: 'llamando'},
                  7: {1: 'llamado', 2: 'llamado', 3: 'llamado', 4: 'llamado', 5: 'llamado', 6: 'llamado'}},
              70: {1: {1: 'escucho', 2: 'escuchas', 3: 'escucha', 4: 'escuchamos', 5: 'escucháis', 6: 'escuchan'},
                  2: {1: 'escuché', 2: 'escuchaste', 3: 'escuchó', 4: 'escuchamos', 5: 'escuchasteis', 6: 'escucharon'},
                  3: {1: 'escuchaba', 2: 'escuchabas', 3: 'escuchaba', 4: 'escuchábamos', 5: 'escuchabais', 6: 'escuchaban'},
                  4: {1: 'escucharé', 2: 'escucharás', 3: 'escuchará', 4: 'escucharemos', 5: 'escucharéis', 6: 'escucharán'},
                  5: {1: 'escucharía', 2: 'escucharías', 3: 'escucharía', 4: 'escucharíamos', 5: 'escucharíais', 6: 'escucharían'},
                  6: {1: 'escuchando', 2: 'escuchando', 3: 'escuchando', 4: 'escuchando', 5: 'escuchando', 6: 'escuchando'},
                  7: {1: 'escuchado', 2: 'escuchado', 3: 'escuchado', 4: 'escuchado', 5: 'escuchado', 6: 'escuchado'}}}
              
nameDict = {1: {'verbName': 'caer', 'tranNameIt': 'cadere', 'tranNameEn': 'to fall'},
            2: {'verbName': 'conseguir', 'tranNameIt': 'conseguire', 'tranNameEn': 'to achieve'},
            3: {'verbName': 'almorzar', 'tranNameIt': 'pranzare', 'tranNameEn': 'to have lunch'},
            4: {'verbName': 'comenzar', 'tranNameIt': 'cominciare', 'tranNameEn': 'to start'},
            5: {'verbName': 'conducir', 'tranNameIt': 'condurre', 'tranNameEn': 'to conduct'},
            6: {'verbName': 'probar', 'tranNameIt': 'provare', 'tranNameEn': 'to try'},
            7: {'verbName': 'jugar', 'tranNameIt': 'giocare', 'tranNameEn': 'to play'},
            8: {'verbName': 'creer', 'tranNameIt': 'credere', 'tranNameEn': 'to believe'},
            9: {'verbName': 'volver', 'tranNameIt': 'ritornare', 'tranNameEn': 'to return'},
            10: {'verbName': 'servir', 'tranNameIt': 'servire', 'tranNameEn': 'to serve'},
            11: {'verbName': 'leer', 'tranNameIt': 'leggere', 'tranNameEn': 'to read'},
            12: {'verbName': 'buscar', 'tranNameIt': 'cercare', 'tranNameEn': 'to search'},
            13: {'verbName': 'apagar', 'tranNameIt': 'spegnere', 'tranNameEn': 'to turn off'},
            14: {'verbName': 'haber', 'tranNameIt': 'avere', 'tranNameEn': 'to have'},
            15: {'verbName': 'oír', 'tranNameIt': 'udire', 'tranNameEn': 'to hear'},
            16: {'verbName': 'recoger', 'tranNameIt': 'raccogliere', 'tranNameEn': 'to collect'},
            17: {'verbName': 'tocar', 'tranNameIt': 'toccare/suonare uno strumento', 'tranNameEn': 'to touch/to play an instrument'},
            18: {'verbName': 'empezar', 'tranNameIt': 'iniziare', 'tranNameEn': 'to begin'},
            19: {'verbName': 'caber', 'tranNameIt': 'entrare (adattarsi)', 'tranNameEn': 'to fit'},
            20: {'verbName': 'llegar', 'tranNameIt': 'arrivare', 'tranNameEn': 'to arrive'},
            21: {'verbName': 'explicar', 'tranNameIt': 'spiegare', 'tranNameEn': 'to explain'},
            22: {'verbName': 'sacar', 'tranNameIt': 'far uscire', 'tranNameEn': 'to take out'},
            23: {'verbName': 'recordar', 'tranNameIt': 'ricordare', 'tranNameEn': 'to remember'},
            24: {'verbName': 'mostrar', 'tranNameIt': 'mostrare', 'tranNameEn': 'to show'},
            25: {'verbName': 'pagar', 'tranNameIt': 'pagare', 'tranNameEn': 'to pay'},
            26: {'verbName': 'entregar', 'tranNameIt': 'consegnare', 'tranNameEn': 'to deliver'},
            27: {'verbName': 'pegar', 'tranNameIt': 'colpire/incollare', 'tranNameEn': 'to hit/to stick'},
            28: {'verbName': 'ser', 'tranNameIt': 'essere', 'tranNameEn': 'to be'},
            29: {'verbName': 'poner', 'tranNameIt': 'mettere', 'tranNameEn': 'to put'},
            30: {'verbName': 'poder', 'tranNameIt': 'potere', 'tranNameEn': 'to can'},
            31: {'verbName': 'decir', 'tranNameIt': 'dire', 'tranNameEn': 'to say'},
            32: {'verbName': 'conocer', 'tranNameIt': 'conoscere', 'tranNameEn': 'to know'},
            33: {'verbName': 'estar', 'tranNameIt': 'essere/stare', 'tranNameEn': 'to be/to stay'},
            34: {'verbName': 'hacer', 'tranNameIt': 'fare', 'tranNameEn': 'to make/to do'},
            35: {'verbName': 'querer', 'tranNameIt': 'volere', 'tranNameEn': 'to want'},
            36: {'verbName': 'encontrar', 'tranNameIt': 'trovare', 'tranNameEn': 'to find'},
            37: {'verbName': 'parecer', 'tranNameIt': 'sembrare', 'tranNameEn': 'to seem'},
            38: {'verbName': 'ir', 'tranNameIt': 'andare', 'tranNameEn': 'to go'},
            39: {'verbName': 'tener (que)', 'tranNameIt': 'avere', 'tranNameEn': 'to have (to)'},
            40: {'verbName': 'pensar', 'tranNameIt': 'pensare', 'tranNameEn': 'to think'},
            41: {'verbName': 'cerrar', 'tranNameIt': 'chiudere', 'tranNameEn': 'to close'},
            42: {'verbName': 'acostarse', 'tranNameIt': 'andare a letto', 'tranNameEn': 'to go to bed'},
            43: {'verbName': 'dar', 'tranNameIt': 'dare', 'tranNameEn': 'to give'},
            44: {'verbName': 'ver', 'tranNameIt': 'vedere/guardare', 'tranNameEn': 'to see/to watch'},
            45: {'verbName': 'venir', 'tranNameIt': 'venire', 'tranNameEn': 'to come'},
            46: {'verbName': 'perder', 'tranNameIt': 'perdere', 'tranNameEn': 'to lose'},
            47: {'verbName': 'traer', 'tranNameIt': 'portare', 'tranNameEn': 'to bring'},
            48: {'verbName': 'encender', 'tranNameIt': 'accendere', 'tranNameEn': 'to turn on/to light'},
            49: {'verbName': 'saber', 'tranNameIt': 'sapere', 'tranNameEn': 'to know'},
            50: {'verbName': 'dormir', 'tranNameIt': 'dormire', 'tranNameEn': 'to sleep'},
            51: {'verbName': 'entender', 'tranNameIt': 'capire', 'tranNameEn': 'to understand'},
            52: {'verbName': 'pedir', 'tranNameIt': 'chiedere', 'tranNameEn': 'to ask'},
            53: {'verbName': 'preferir', 'tranNameIt': 'preferire', 'tranNameEn': 'to prefer'},
            54: {'verbName': 'seguir', 'tranNameIt': 'seguire', 'tranNameEn': 'to follow'},
            55: {'verbName': 'sentirse', 'tranNameIt': 'sentirsi', 'tranNameEn': 'to feel oneself'},
            56: {'verbName': 'sentarse', 'tranNameIt': 'sedersi', 'tranNameEn': 'to sit'},
            57: {'verbName': 'oler', 'tranNameIt': 'annusare', 'tranNameEn': 'to smell'},
            58: {'verbName': 'practicar', 'tranNameIt': 'praticare', 'tranNameEn': 'to practice'},
            59: {'verbName': 'amar', 'tranNameIt': 'amare', 'tranNameEn': 'to love'},
            60: {'verbName': 'comer', 'tranNameIt': 'mangiare', 'tranNameEn': 'to eat'},
            61: {'verbName': 'vivir', 'tranNameIt': 'vivere', 'tranNameEn': 'to live'},
            62: {'verbName': 'bailar', 'tranNameIt': 'ballare', 'tranNameEn': 'to dance'},
            63: {'verbName': 'cantar', 'tranNameIt': 'cantare', 'tranNameEn': 'to sing'},
            64: {'verbName': 'comprar', 'tranNameIt': 'comprare', 'tranNameEn': 'to buy'},
            65: {'verbName': 'trabajar', 'tranNameIt': 'lavorare', 'tranNameEn': 'to work'},
            66: {'verbName': 'tomar', 'tranNameIt': 'prendere', 'tranNameEn': 'to take'},
            67: {'verbName': 'cocinar', 'tranNameIt': 'cucinare', 'tranNameEn': 'to cook'},
            68: {'verbName': 'enseñar', 'tranNameIt': 'insegnare', 'tranNameEn': 'to teach'},
            69: {'verbName': 'llamar', 'tranNameIt': 'chiamare', 'tranNameEn': 'to call/to name'},
            70: {'verbName': 'escuchar', 'tranNameIt': 'ascoltare', 'tranNameEn': 'to listen to'}}

correct = 0
wrong = 0

welcomeIt = 'Ciao, con questo semplice software potrai esercitarti nella coniugazione dei verbi in spagnolo. Per terminare la sessione premi Enter. Iniziamo subito!'
welcomeEn = 'Hi, this simple software allows you to practice the conjugation of Spanish verbs. To ends the exercise press Enter. Lets start!'
tenseIt = 'Che tempo verbale vuoi praticare? Presente = 1; Passato semplice = 2; Imperfetto = 3; Futuro = 4; Condizionale = 5; Gerundio = 6; Participio passato = 7; Tutti = 8.'

print('\n \n')
print(welcomeIt)
print('\n \n')
print(tenseIt)
print('\n \n')

tenseSelect2 = input()
tenseSelect = int(tenseSelect2)

while True:
    if tenseSelect == 8:
        tens = random.randint(1, 7)
    else:
        tens = tenseSelect
    verb = random.randint(1, 70)
    pers = random.randint(1, 6)

    if tens == 1:
        tensNameIt = 'presente'
    elif tens == 2:
        tensNameIt = 'passato semplice'
    elif tens == 3:
        tensNameIt = 'imperfetto'
    elif tens == 4:
        tensNameIt = 'futuro'
    elif tens == 5:
        tensNameIt = 'condizionale'
    elif tens == 6:
        tensNameIt = 'Gerundio'
    elif tens == 7:
        tensNameIt = 'Participio passato'
    if pers == 1:
        persNameIt = '1a persona singolare (yo)'
    elif pers == 2:
        persNameIt = '2a persona singolare (tú)'
    elif pers == 3:
        persNameIt = '3a persona singolare (él, ella)'
    elif pers == 4:
        persNameIt = '1a persona plurale (nosotros)'
    elif pers == 5:
        persNameIt = '2a persona plurale (vosotros)'
    else:
        persNameIt = '3a persona plurale (ellos, ellas)'
    
    quest = {verbDict[verb][tens][pers]}
    verbQuest = {nameDict[verb]['verbName']}
    tranQuest = {nameDict[verb]['tranNameIt']}
    questStr = ' '.join(map(str, quest))
    verbQuestStr = ' '.join(map(str, verbQuest))
    tranQuestStr = ' '.join(map(str, tranQuest))

    if tens < 6:
        print(persNameIt + ' ' + tensNameIt + ' del verbo ' + verbQuestStr + ' (' + tranQuestStr + ') :')
    else:
        print(tensNameIt + ' del verbo ' + verbQuestStr + ' (' + tranQuestStr + ') :')
        
    answ = input()
    if answ == '':
        print('\n\nSessione terminata, hai dato ' + str(correct) + ' risposte esatte e ' + str(wrong) + ' risposte sbagliate. \n')
        break
    elif answ.lower() == questStr:
        correct = correct + 1
        if correct == 1:
            print('\nCorretto, ' + answ + ' è la risposta esatta! Hai dato ' + str(correct) + ' risposta esatta. \n \n')
        else:
            print('\nCorretto, ' + answ + ' è la risposta esatta! Hai dato ' + str(correct) + ' risposte esatte. \n \n')
    else:
        wrong = wrong + 1
        if wrong == 1:
            print('\nSbagliato, ' + answ + ' è incorretto, la risposta esatta è ' + questStr + '. Hai dato ' + str(wrong) + ' risposta errata. \n \n')
        else:
            print('\nSbagliato, ' + answ + ' è incorretto, la risposta esatta è ' + questStr + '. Hai dato ' + str(wrong) + ' risposte errate. \n \n')
